# Generated by Django 4.2.13 on 2024-06-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
    ]
